# use normal make for this Makefile
#
# Makefile for building user programs to run on top of Nachos
#
# Several things to be aware of:
#
#    Nachos assumes that the location of the program startup routine (the
# 	location the kernel jumps to when the program initially starts up)
#       is at location 0.  This means: start.o must be the first .o passed 
# 	to ld, in order for the routine "Start" to be loaded at location 0
#

# if you are cross-compiling, you need to point to the right executables
# and change the flags to ld and the build procedure for as

GCCDIR = ../../../gnu-decstation-ultrix/decstation-ultrix/2.95.3/

LDFLAGS = -T script -N
ASFLAGS = -mips2
CPPFLAGS = $(INCDIR)

# if you aren't cross-compiling:
# GCCDIR =
# LDFLAGS = -N -T 0
# ASFLAGS =
# CPPFLAGS = -P $(INCDIR)

PATH = $(GCCDIR):/lib:/usr/bin:/bin

CC = $(GCCDIR)gcc -B../../../gnu-decstation-ultrix/
AS = $(GCCDIR)as
LD = $(GCCDIR)ld

CPP = gcc -E
INCDIR =-I../userprog -I../threads
CFLAGS = -G 0 -c $(INCDIR)

all: halt shell matmult sort Createfile Echo Cat Copy Delete ping pong scheduler

start.o: start.s ../userprog/syscall.h
	$(CPP) $(CPPFLAGS) start.c > strt.s
	$(AS) $(ASFLAGS) -o start.o strt.s
	rm strt.s

halt.o: halt.c
	$(CC) $(CFLAGS) -c halt.c
halt: halt.o start.o
	$(LD) $(LDFLAGS) start.o halt.o -o halt.coff
	../bin/coff2noff halt.coff halt

shell.o: shell.c
	$(CC) $(CFLAGS) -c shell.c
shell: shell.o start.o
	$(LD) $(LDFLAGS) start.o shell.o -o shell.coff
	../bin/coff2noff shell.coff shell

sort.o: sort.c
	$(CC) $(CFLAGS) -c sort.c
sort: sort.o start.o
	$(LD) $(LDFLAGS) start.o sort.o -o sort.coff
	../bin/coff2noff sort.coff sort

matmult.o: matmult.c
	$(CC) $(CFLAGS) -c matmult.c
matmult: matmult.o start.o
	$(LD) $(LDFLAGS) start.o matmult.o -o matmult.coff
	../bin/coff2noff matmult.coff matmult

Createfile.o: Createfile.c
	$(CC) $(CFLAGS) -c Createfile.c
Createfile: Createfile.o start.o
	$(LD) $(LDFLAGS) start.o Createfile.o -o Createfile.coff
	../bin/coff2noff Createfile.coff Createfile

Echo.o: Echo.c
	$(CC) $(CFLAGS) -c Echo.c
Echo: Echo.o start.o
	$(LD) $(LDFLAGS) start.o Echo.o -o Echo.coff
	../bin/coff2noff Echo.coff Echo

Cat.o: Cat.c
	$(CC) $(CFLAGS) -c Cat.c
Cat: Cat.o start.o
	$(LD) $(LDFLAGS) start.o Cat.o -o Cat.coff
	../bin/coff2noff Cat.coff Cat

Copy.o: Copy.c
	$(CC) $(CFLAGS) -c Copy.c
Copy: Copy.o start.o
	$(LD) $(LDFLAGS) start.o Copy.o -o Copy.coff
	../bin/coff2noff Copy.coff Copy

Delete.o: Delete.c
	$(CC) $(CFLAGS) -c Delete.c
Delete: Delete.o start.o
	$(LD) $(LDFLAGS) start.o Delete.o -o Delete.coff
	../bin/coff2noff Delete.coff Delete

ping.o: ping.c
	$(CC) $(CFLAGS) -c ping.c
ping: ping.o start.o
	$(LD) $(LDFLAGS) start.o ping.o -o ping.coff
	../bin/coff2noff ping.coff ping

pong.o: pong.c
	$(CC) $(CFLAGS) -c pong.c
pong: pong.o start.o
	$(LD) $(LDFLAGS) start.o pong.o -o pong.coff
	../bin/coff2noff pong.coff pong

scheduler.o: scheduler.c
	$(CC) $(CFLAGS) -c scheduler.c
scheduler: scheduler.o start.o
	$(LD) $(LDFLAGS) start.o scheduler.o -o scheduler.coff
	../bin/coff2noff scheduler.coff scheduler
